//! naivi-wasm — generic U5/U7 wasm channel for the naivi (Vue Vapor) frontend.
//!
//! A `cdylib` exposing the binary-frame transport as wasm-bindgen exports
//! (U7): the guest queues DOM changes into a [`FrameWriter`] and flushes one
//! frame per boundary via [`flush_frame`]; events return per-callback via
//! [`set_event_callback`], and whole-frame rejections arrive via
//! [`set_frame_rejected_callback`] (self-heal, R15). A single
//! [`NaiviDocument`] is created by [`start`] and driven by
//! [`BlitzApplication`] (winit + VelloHybrid renderer on the `#blitz-target`
//! canvas).
//!
//! This is the SHARED wasm host: `naivi wasm --release` (in any
//! `examples/naivi/<demo>`) drops the demo's guest bundle into this crate's
//! `assets/guest/`, and `trunk serve` (here) runs it. There are no per-demo
//! host crates.
//!
//! ## Protocol notes (shared with `js/naivi-runtime/src/wasm-types.ts`)
//!
//! - DOM changes: one binary frame per flush (`[seq u32][count u16][op…]`,
//!   virtual u32 node ids — KD3). No per-op exports.
//! - Event kinds are encoded as `u8`, matching [`NaiviEventKind`]'s generated
//!   `to_u8`/`from_u8` (click=0 … input=11); the JS side mirrors that in
//!   `EVENT_KINDS` (the `@naivi/protocol` SOT).
//! - `set_event_callback` receives `(nodeId, kind, x, y, key, code, value)` per
//!   drained event (nodeId = the JS-assigned virtual id; key/code for keyboard
//!   events, the full value for `input`).
//! - `set_frame_rejected_callback` receives `(seq, reason)` when a whole frame
//!   is discarded (KTD3).

#![cfg(target_arch = "wasm32")]

use std::cell::RefCell;
use std::rc::Rc;

use anyrender_vello_hybrid::VelloHybridWindowRenderer;
use blitz_dom::{BaseDocument, DocGuard, DocGuardMut, Document, DocumentConfig, build_single_font_ctx};
use blitz_shell::{BlitzApplication, BlitzShellProxy, WindowConfig};
use blitz_traits::events::UiEvent;
use naivi_dom::{EventSink, NaiviDocument, NaiviEvent};
use std::task::Context as TaskContext;
use tracing::info;
use wasm_bindgen::prelude::*;
use winit::event_loop::EventLoop;
use winit::platform::web::WindowAttributesWeb;
use winit::window::WindowAttributes;

/// DejaVu Sans, bundled so the document has a real font on wasm32 (browsers
/// don't expose system fonts to wasm). License: Bitstream Vera / DejaVu
/// (permissive).
const DEJAVU_SANS: &[u8] = include_bytes!("../assets/DejaVuSans.woff2");

thread_local! {
    /// The single naivi document, installed by [`start`] before `run_app`.
    static DOC: RefCell<Option<Rc<RefCell<NaiviDocument>>>> = const { RefCell::new(None) };
    /// The JS callback registered via [`set_event_callback`].
    static EVENT_CALLBACK: RefCell<Option<js_sys::Function>> = const { RefCell::new(None) };
    /// The JS callback registered via [`set_frame_rejected_callback`].
    static REJECTED_CALLBACK: RefCell<Option<js_sys::Function>> = const { RefCell::new(None) };
}

// ── event kind <-> u8 (generated by naivi-dom from the @naivi/protocol SOT) ──

/// Sink that forwards drained events to the JS callback as
/// `(nodeId, kind, x, y, key, code, value, button, buttons, deltaX, deltaY,
/// imeData, chain)` — the `set_event_callback` wire shape (KTD2/KTD3).
struct WasmEventSink;

impl EventSink for WasmEventSink {
    fn on_event(&mut self, event: NaiviEvent) {
        EVENT_CALLBACK.with(|slot| {
            let slot = slot.borrow();
            let Some(cb) = slot.as_ref() else {
                return;
            };
            let args = js_sys::Array::new();
            args.push(&JsValue::from_f64(event.node as f64));
            args.push(&JsValue::from(event.kind.to_u8()));
            args.push(&JsValue::from_f64(event.client_x as f64));
            args.push(&JsValue::from_f64(event.client_y as f64));
            args.push(&JsValue::from_str(&event.key));
            args.push(&JsValue::from_str(&event.code));
            args.push(&JsValue::from_str(&event.value));
            args.push(&JsValue::from_f64(event.button as f64));
            args.push(&JsValue::from_f64(event.buttons as f64));
            args.push(&JsValue::from_f64(event.delta_x));
            args.push(&JsValue::from_f64(event.delta_y));
            args.push(&JsValue::from_str(&event.ime_data));
            // Ordered bound chain (KTD3) as a trailing array argument.
            let chain = js_sys::Array::new();
            for id in &event.chain {
                chain.push(&JsValue::from_f64(*id as f64));
            }
            args.push(&chain);
            let _ = cb.apply(&JsValue::NULL, &args);
        });
    }
}

/// Forwards the blitz [`Document`] surface to the shared naivi document so the
/// SAME instance (and its shared event bindings/queue) serves both the window
/// and the wasm exports' ops core.
///
/// Holds a clone of `NaiviDocument::inner` so [`Document::inner`]/[`inner_mut`]
/// borrow from a long-lived [`Rc<RefCell<BaseDocument>>`] (the same pattern
/// blitz uses for `Rc<RefCell<BaseDocument>>: Document`).
///
/// `poll` uses an immutable borrow: `NaiviDocument::drain_events` is `&self`
/// and the JS sink may re-enter Rust (Vue handler → wasm export) synchronously
/// while it runs. A mutable borrow held across that call would trip the
/// `RefCell` re-entrancy guard.
struct DocHandle {
    /// The naivi document (owns bindings + event queue + sink).
    doc: Rc<RefCell<NaiviDocument>>,
    /// Clone of `doc.inner`, kept so `inner()`/`inner_mut()` can return
    /// borrows from a source that outlives the call.
    inner: Rc<RefCell<BaseDocument>>,
}

impl DocHandle {
    fn new(doc: Rc<RefCell<NaiviDocument>>) -> Self {
        let inner = Rc::clone(&doc.borrow().inner);
        Self { doc, inner }
    }
}

impl Document for DocHandle {
    fn inner(&self) -> DocGuard<'_> {
        DocGuard::RefCell(self.inner.borrow())
    }

    fn inner_mut(&mut self) -> DocGuardMut<'_> {
        DocGuardMut::RefCell(self.inner.borrow_mut())
    }

    fn handle_ui_event(&mut self, event: UiEvent) {
        // The naivi event handler only records into the queue — no JS re-entry.
        self.doc.borrow_mut().handle_ui_event(event);
    }

    fn poll(&mut self, _task_context: Option<TaskContext>) -> bool {
        // `&self`: the sink may re-enter Rust synchronously via the JS callback.
        self.doc.borrow().drain_events()
    }
}

// ── frame transport exports (U7; KD1/KD3/KD8) ──────────────────────

/// Flush one binary DOM-change frame (the ONLY DOM-mutation entry; U4 wire
/// format, virtual u32 node ids). Applied as a whole transaction; a rejected
/// frame is discarded untouched and `frame_rejected(seq, reason)` is delivered
/// to the callback installed via [`set_frame_rejected_callback`].
#[wasm_bindgen]
pub fn flush_frame(bytes: &[u8]) {
    DOC.with(|slot| {
        let slot = slot.borrow();
        let Some(doc) = slot.as_ref() else {
            return;
        };
        let mut doc_ref = doc.borrow_mut();
        doc_ref.flush_frame(bytes);
        let rejected = doc_ref.take_frame_rejected();
        drop(doc_ref);
        for (seq, reason) in rejected {
            REJECTED_CALLBACK.with(|slot| {
                let slot = slot.borrow();
                if let Some(cb) = slot.as_ref() {
                    let args = js_sys::Array::new();
                    args.push(&JsValue::from_f64(seq as f64));
                    args.push(&JsValue::from_f64(reason as f64));
                    let _ = cb.apply(&JsValue::NULL, &args);
                }
            });
        }
    });
}

/// Register the Rust→JS frame-rejection callback: `(seq, reason) => void`
/// (self-heal trigger, R15). Replaces any previously installed callback.
#[wasm_bindgen]
pub fn set_frame_rejected_callback(cb: js_sys::Function) {
    REJECTED_CALLBACK.with(|slot| *slot.borrow_mut() = Some(cb));
}

/// Register the Rust→JS event callback:
/// `(nodeId, kind, x, y, key, code, value) => void` (per-event, KD2).
#[wasm_bindgen]
pub fn set_event_callback(cb: js_sys::Function) {
    EVENT_CALLBACK.with(|slot| *slot.borrow_mut() = Some(cb));
}

/// Force-drain queued events through the sink (the app loop already does this
/// per frame; kept as a guest-invokable pump).
#[wasm_bindgen]
pub fn tick() {
    DOC.with(|slot| {
        if let Some(doc) = slot.borrow().as_ref() {
            doc.borrow().drain_events();
        }
    });
}

// ── host startup ────────────────────────────────────────────────────

#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    console_error_panic_hook::set_once();
    tracing_wasm::set_as_global_default();
    info!("naivi wasm starting");

    let window = web_sys::window().expect("no global window");
    let document = window.document().expect("no document on window");
    let canvas = document
        .get_element_by_id("blitz-target")
        .expect("no #blitz-target canvas in the host page");
    let canvas = canvas
        .dyn_into::<web_sys::HtmlCanvasElement>()
        .expect("#blitz-target is not a canvas");

    // Make sure the canvas can be given focus and isn't outlined when focused.
    canvas.set_tab_index(0);
    canvas.style().set_property("outline", "none")?;

    let event_loop = EventLoop::new().map_err(|e| JsValue::from_str(&format!("{e}")))?;
    let (proxy, rx) = BlitzShellProxy::new(event_loop.create_proxy());

    let renderer = VelloHybridWindowRenderer::new();
    let mut doc = NaiviDocument::with_config(DocumentConfig {
        font_ctx: Some(build_single_font_ctx(DEJAVU_SANS)),
        ..Default::default()
    });
    doc.set_event_sink(Box::new(WasmEventSink));
    let doc = Rc::new(RefCell::new(doc));

    // Install the document in global state BEFORE run_app so any guest op
    // issued after the first frame resolves against it.
    DOC.with(|slot| *slot.borrow_mut() = Some(Rc::clone(&doc)));

    // Intentionally no `.with_surface_size(...)` on wasm: letting winit-web set
    // the canvas size writes fixed inline CSS that overrides host stylesheet
    // rules. Host CSS sizes the canvas.
    let attrs = WindowAttributes::default().with_platform_attributes(Box::new(
        WindowAttributesWeb::default().with_canvas(Some(canvas)),
    ));
    let window_config = WindowConfig::with_attributes(Box::new(DocHandle::new(doc)), renderer, attrs);

    let mut app = BlitzApplication::<VelloHybridWindowRenderer>::new(proxy, rx);
    app.add_window(window_config);

    event_loop
        .run_app(app)
        .map_err(|e| JsValue::from_str(&format!("{e}")))?;
    Ok(())
}
