//! Event binding, queueing and sink plumbing for naivi.

use crate::ops::{DATA_NAIVI_ID, NaiviBindings};
use blitz_dom::{Document, EventHandler, LocalName};
use blitz_traits::events::{
    BlitzImeEvent, BlitzWheelDelta, DomEvent, DomEventData, DomEventKind, EventState,
};
use blitz_traits::node_id::NodeId;
use std::cell::RefCell;
use std::collections::VecDeque;
use std::rc::Rc;

/// The full set of DOM event kinds that naivi can bind Vue `v-on` handlers to
/// (plan 076: engine `DomEventKind` 全 34 种对齐).
///
/// Generated by `build.rs` from the `@naivi/protocol` SOT — the protocol half
/// (enum, `ALL`, `name`, `to_u8`/`from_u8`, `FromStr`) is generated, do not
/// hand-edit it. Only the blitz mapping impls below are hand-written (TS can't
/// express blitz's Rust `DomEventKind`).
pub use crate::generated::NaiviEventKind;

impl NaiviEventKind {
    /// Whether this kind does **not** bubble in naivi (KD5): only the chain
    /// head is dispatched. `mouseenter`/`mouseleave` are the naivi-fixed
    /// non-bubbling set; the engine already prunes `scroll`/`focus`/`blur`/
    /// `pointerenter`/`pointerleave`/`applekeybinding` to `[target]`, so they
    /// never reach ancestors regardless.
    pub fn is_non_bubbling(self) -> bool {
        matches!(self, Self::MouseEnter | Self::MouseLeave)
    }

    /// Map a blitz [`DomEvent`] to the corresponding naivi kind.
    ///
    /// Returns `None` for event kinds naivi does not expose to the guest
    /// (none remain — the wire table covers all 34 engine kinds).
    pub fn from_dom_event(event: &DomEvent) -> Option<Self> {
        match &event.data {
            DomEventData::Click(_) => Some(Self::Click),
            DomEventData::PointerDown(_) => Some(Self::PointerDown),
            DomEventData::PointerUp(_) => Some(Self::PointerUp),
            DomEventData::PointerMove(_) => Some(Self::PointerMove),
            DomEventData::PointerCancel(_) => Some(Self::PointerCancel),
            DomEventData::PointerEnter(_) => Some(Self::PointerEnter),
            DomEventData::PointerLeave(_) => Some(Self::PointerLeave),
            DomEventData::PointerOver(_) => Some(Self::PointerOver),
            DomEventData::PointerOut(_) => Some(Self::PointerOut),
            DomEventData::MouseMove(_) => Some(Self::MouseMove),
            DomEventData::MouseDown(_) => Some(Self::MouseDown),
            DomEventData::MouseUp(_) => Some(Self::MouseUp),
            DomEventData::MouseEnter(_) => Some(Self::MouseEnter),
            DomEventData::MouseLeave(_) => Some(Self::MouseLeave),
            DomEventData::MouseOver(_) => Some(Self::MouseOver),
            DomEventData::MouseOut(_) => Some(Self::MouseOut),
            DomEventData::TouchStart(_) => Some(Self::TouchStart),
            DomEventData::TouchMove(_) => Some(Self::TouchMove),
            DomEventData::TouchEnd(_) => Some(Self::TouchEnd),
            DomEventData::TouchCancel(_) => Some(Self::TouchCancel),
            DomEventData::Scroll(_) => Some(Self::Scroll),
            DomEventData::Wheel(_) => Some(Self::Wheel),
            DomEventData::ContextMenu(_) => Some(Self::ContextMenu),
            DomEventData::DoubleClick(_) => Some(Self::DblClick),
            DomEventData::KeyPress(_) => Some(Self::KeyPress),
            DomEventData::KeyDown(_) => Some(Self::KeyDown),
            DomEventData::KeyUp(_) => Some(Self::KeyUp),
            DomEventData::Input(_) => Some(Self::Input),
            DomEventData::Ime(_) => Some(Self::Composition),
            DomEventData::Focus(_) => Some(Self::Focus),
            DomEventData::Blur(_) => Some(Self::Blur),
            DomEventData::FocusIn(_) => Some(Self::FocusIn),
            DomEventData::FocusOut(_) => Some(Self::FocusOut),
            DomEventData::AppleStandardKeybinding(_) => Some(Self::AppleKeyBinding),
        }
    }

    /// Map from a blitz [`DomEventKind`].
    pub fn from_dom_event_kind(kind: DomEventKind) -> Option<Self> {
        match kind {
            DomEventKind::Click => Some(Self::Click),
            DomEventKind::PointerDown => Some(Self::PointerDown),
            DomEventKind::PointerUp => Some(Self::PointerUp),
            DomEventKind::PointerMove => Some(Self::PointerMove),
            DomEventKind::PointerCancel => Some(Self::PointerCancel),
            DomEventKind::PointerEnter => Some(Self::PointerEnter),
            DomEventKind::PointerLeave => Some(Self::PointerLeave),
            DomEventKind::PointerOver => Some(Self::PointerOver),
            DomEventKind::PointerOut => Some(Self::PointerOut),
            DomEventKind::MouseMove => Some(Self::MouseMove),
            DomEventKind::MouseDown => Some(Self::MouseDown),
            DomEventKind::MouseUp => Some(Self::MouseUp),
            DomEventKind::MouseEnter => Some(Self::MouseEnter),
            DomEventKind::MouseLeave => Some(Self::MouseLeave),
            DomEventKind::MouseOver => Some(Self::MouseOver),
            DomEventKind::MouseOut => Some(Self::MouseOut),
            DomEventKind::TouchStart => Some(Self::TouchStart),
            DomEventKind::TouchMove => Some(Self::TouchMove),
            DomEventKind::TouchEnd => Some(Self::TouchEnd),
            DomEventKind::TouchCancel => Some(Self::TouchCancel),
            DomEventKind::Scroll => Some(Self::Scroll),
            DomEventKind::Wheel => Some(Self::Wheel),
            DomEventKind::ContextMenu => Some(Self::ContextMenu),
            DomEventKind::DoubleClick => Some(Self::DblClick),
            DomEventKind::KeyPress => Some(Self::KeyPress),
            DomEventKind::KeyDown => Some(Self::KeyDown),
            DomEventKind::KeyUp => Some(Self::KeyUp),
            DomEventKind::Input => Some(Self::Input),
            DomEventKind::Ime => Some(Self::Composition),
            DomEventKind::Focus => Some(Self::Focus),
            DomEventKind::Blur => Some(Self::Blur),
            DomEventKind::FocusIn => Some(Self::FocusIn),
            DomEventKind::FocusOut => Some(Self::FocusOut),
            DomEventKind::AppleStandardKeybinding => Some(Self::AppleKeyBinding),
        }
    }

    /// Map to a blitz [`DomEventKind`].
    pub fn to_dom_event_kind(self) -> DomEventKind {
        match self {
            Self::Click => DomEventKind::Click,
            Self::PointerDown => DomEventKind::PointerDown,
            Self::PointerUp => DomEventKind::PointerUp,
            Self::PointerMove => DomEventKind::PointerMove,
            Self::PointerCancel => DomEventKind::PointerCancel,
            Self::PointerEnter => DomEventKind::PointerEnter,
            Self::PointerLeave => DomEventKind::PointerLeave,
            Self::PointerOver => DomEventKind::PointerOver,
            Self::PointerOut => DomEventKind::PointerOut,
            Self::MouseMove => DomEventKind::MouseMove,
            Self::MouseDown => DomEventKind::MouseDown,
            Self::MouseUp => DomEventKind::MouseUp,
            Self::MouseEnter => DomEventKind::MouseEnter,
            Self::MouseLeave => DomEventKind::MouseLeave,
            Self::MouseOver => DomEventKind::MouseOver,
            Self::MouseOut => DomEventKind::MouseOut,
            Self::TouchStart => DomEventKind::TouchStart,
            Self::TouchMove => DomEventKind::TouchMove,
            Self::TouchEnd => DomEventKind::TouchEnd,
            Self::TouchCancel => DomEventKind::TouchCancel,
            Self::Scroll => DomEventKind::Scroll,
            Self::Wheel => DomEventKind::Wheel,
            Self::ContextMenu => DomEventKind::ContextMenu,
            Self::DblClick => DomEventKind::DoubleClick,
            Self::KeyPress => DomEventKind::KeyPress,
            Self::KeyDown => DomEventKind::KeyDown,
            Self::KeyUp => DomEventKind::KeyUp,
            Self::Input => DomEventKind::Input,
            Self::Composition => DomEventKind::Ime,
            Self::Focus => DomEventKind::Focus,
            Self::Blur => DomEventKind::Blur,
            Self::FocusIn => DomEventKind::FocusIn,
            Self::FocusOut => DomEventKind::FocusOut,
            Self::AppleKeyBinding => DomEventKind::AppleStandardKeybinding,
        }
    }
}

/// A single event queued for the naivi guest.
#[derive(Debug, Clone, PartialEq)]
pub struct NaiviEvent {
    /// The JS-assigned **virtual id** of the node that carried the matching
    /// binding (reverse-looked-up from the node's `data-naivi-id` attribute at
    /// queue time, KTD2). `0` when the node has no such attribute (legacy
    /// per-op binding; the guest cannot resolve it).
    pub node: u32,
    /// The **ordered bound chain** (KTD3): every node on the engine's hit
    /// chain — target first, then ancestors — that has this kind bound and a
    /// resolvable virtual id. `node` is `chain[0]`; JS dispatches along this
    /// chain so `stopPropagation` can truncate (KTD3). Empty never occurs on
    /// a queued event (the handler drops chainless events).
    pub chain: Vec<u32>,
    /// The event kind.
    pub kind: NaiviEventKind,
    /// Client (viewport-relative) coordinates, when the underlying DOM event
    /// carried them (0.0 otherwise).
    pub client_x: f32,
    pub client_y: f32,
    /// The keyboard key (e.g. `"Enter"`, `"a"`) for key events; empty
    /// otherwise.
    pub key: String,
    /// The physical keyboard code (e.g. `"Enter"`, `"KeyA"`) for key events;
    /// empty otherwise.
    pub code: String,
    /// The full input value for `input` events (the engine's text-input
    /// editor syncs it on every keystroke); empty otherwise.
    pub value: String,
    /// The mouse button that triggered the event (`0` = main, `1` = auxiliary,
    /// `2` = secondary, `3` = fourth, `4` = fifth) for pointer/mouse/touch/
    /// click/contextmenu/dblclick events; `0` otherwise.
    pub button: u16,
    /// Bitmask of currently-pressed mouse buttons for pointer/mouse/touch
    /// events; `0` otherwise.
    pub buttons: u16,
    /// Wheel delta (`x`/`y`, pixels or lines, sign per scroll direction) for
    /// `wheel` events; `0.0` otherwise. The engine's `Scroll` event has no
    /// delta fields (OQ1), so scroll always carries `0.0`.
    pub delta_x: f64,
    pub delta_y: f64,
    /// The IME composition commit text for `composition` events (engine
    /// `Ime(Commit)`); empty otherwise (OQ2).
    pub ime_data: String,
}

/// Receives events drained from [`NaiviDocument`](crate::document::NaiviDocument)'s queue.
///
/// U4 (wasm) and U5 (rquickjs) provide their own impls; the default is a no-op.
pub trait EventSink {
    fn on_event(&mut self, event: NaiviEvent);
}

/// A sink that discards every event (the default).
pub struct NoopEventSink;

impl EventSink for NoopEventSink {
    fn on_event(&mut self, _event: NaiviEvent) {}
}

/// A blitz [`EventHandler`] that only records matching events into the shared queue.
///
/// It never mutates the DOM or calls back into the guest: it consults the
/// binding registry for the first node in the event's chain that has the
/// event kind bound, and pushes the event onto the queue. The queue is
/// drained later by [`NaiviDocument::poll`](crate::document::NaiviDocument::poll),
/// which avoids re-entering blitz's event dispatch while `EventDriver` holds
/// `&mut dyn Document`.
pub struct NaiviEventHandler {
    pub(crate) bindings: Rc<RefCell<NaiviBindings>>,
    pub(crate) queue: Rc<RefCell<VecDeque<NaiviEvent>>>,
}

impl EventHandler for NaiviEventHandler {
    fn handle_event(
        &mut self,
        chain: &[NodeId],
        event: &mut DomEvent,
        doc: &mut dyn Document,
        _event_state: &mut EventState,
    ) {
        let Some(kind) = NaiviEventKind::from_dom_event(event) else {
            return;
        };
        let (client_x, client_y) = client_coords(&event.data);
        let (key, code, value) = event_payload(&event.data);
        let (button, buttons) = pointer_buttons(&event.data);
        let (delta_x, delta_y) = wheel_delta(&event.data);
        let ime_data = ime_text(&event.data);
        let bindings = self.bindings.borrow();
        // Collect every chain node (target first, then ancestors) that has this
        // kind bound AND a resolvable `data-naivi-id` (KTD3). The frame
        // `bind_event_v` writes the virtual id there; a missing/unparseable
        // value skips the node (the guest cannot resolve it). Non-bubbling
        // kinds (KD5: mouseenter/mouseleave) only take the head — the engine
        // already prunes scroll/focus/blur/pointerenter/leave/applekeybinding
        // to `[target]`.
        let mut chain_ids: Vec<u32> = Vec::new();
        for node in chain.iter().copied() {
            if !bindings.get(&node).is_some_and(|kinds| kinds.contains(&kind)) {
                continue;
            }
            let Some(virtual_id) = doc
                .inner()
                .get_node(node)
                .and_then(|n| n.attr(LocalName::from(DATA_NAIVI_ID)))
                .and_then(|s| s.parse::<u32>().ok())
            else {
                continue;
            };
            chain_ids.push(virtual_id);
            if kind.is_non_bubbling() {
                break;
            }
        }
        drop(bindings);
        if chain_ids.is_empty() {
            return;
        }
        // Chain head (deepest bound node) stays in `node` (existing single-node
        // semantics); the full ordered chain rides in `chain` (KTD3).
        self.queue.borrow_mut().push_back(NaiviEvent {
            node: chain_ids[0],
            chain: chain_ids,
            kind,
            client_x,
            client_y,
            key,
            code,
            value,
            button,
            buttons,
            delta_x,
            delta_y,
            ime_data,
        });
    }
}

/// Capture the pressed mouse button + buttons bitmask from a [`DomEventData`]
/// (`0`/`0` for non-pointer kinds).
fn pointer_buttons(data: &DomEventData) -> (u16, u16) {
    use DomEventData::*;
    match data {
        PointerMove(e)
        | PointerDown(e)
        | PointerUp(e)
        | PointerCancel(e)
        | PointerEnter(e)
        | PointerLeave(e)
        | PointerOver(e)
        | PointerOut(e)
        | MouseMove(e)
        | MouseDown(e)
        | MouseUp(e)
        | MouseEnter(e)
        | MouseLeave(e)
        | MouseOver(e)
        | MouseOut(e)
        | TouchStart(e)
        | TouchMove(e)
        | TouchEnd(e)
        | TouchCancel(e)
        | Click(e)
        | ContextMenu(e)
        | DoubleClick(e) => (e.button as u16, e.buttons.bits() as u16),
        _ => (0, 0),
    }
}

/// Capture the wheel delta (lines or pixels) from a [`DomEventData`]; `0.0`
/// otherwise.
fn wheel_delta(data: &DomEventData) -> (f64, f64) {
    match data {
        DomEventData::Wheel(e) => match e.delta {
            BlitzWheelDelta::Lines(dx, dy) | BlitzWheelDelta::Pixels(dx, dy) => (dx, dy),
        },
        _ => (0.0, 0.0),
    }
}

/// Capture the IME composition text from a [`DomEventData`] (`Ime(Commit)`);
/// empty otherwise.
fn ime_text(data: &DomEventData) -> String {
    match data {
        DomEventData::Ime(BlitzImeEvent::Commit(text)) => text.to_string(),
        _ => String::new(),
    }
}

/// Cheaply capture client coordinates from a [`DomEventData`] without re-entering blitz.
fn client_coords(data: &DomEventData) -> (f32, f32) {
    use DomEventData::*;
    match data {
        PointerMove(e)
        | PointerDown(e)
        | PointerUp(e)
        | PointerCancel(e)
        | PointerEnter(e)
        | PointerLeave(e)
        | PointerOver(e)
        | PointerOut(e)
        | MouseMove(e)
        | MouseDown(e)
        | MouseUp(e)
        | MouseEnter(e)
        | MouseLeave(e)
        | MouseOver(e)
        | MouseOut(e)
        | TouchStart(e)
        | TouchMove(e)
        | TouchEnd(e)
        | TouchCancel(e)
        | Click(e)
        | ContextMenu(e)
        | DoubleClick(e) => (e.client_x(), e.client_y()),
        Wheel(e) => (e.client_x(), e.client_y()),
        _ => (0.0, 0.0),
    }
}

/// Capture the keyboard/input payload (`(key, code, value)`) from a
/// [`DomEventData`]. Non-keyboard events yield three empty strings.
fn event_payload(data: &DomEventData) -> (String, String, String) {
    match data {
        DomEventData::KeyDown(e) | DomEventData::KeyUp(e) | DomEventData::KeyPress(e) => {
            (e.key.to_string(), e.code.to_string(), String::new())
        }
        DomEventData::Input(e) => (String::new(), String::new(), e.value.clone()),
        _ => (String::new(), String::new(), String::new()),
    }
}
