//! Event binding, queueing and sink plumbing for naivi.

use crate::ops::{DATA_NAIVI_ID, NaiviBindings};
use blitz_dom::{Document, EventHandler, LocalName};
use blitz_traits::events::{DomEvent, DomEventData, DomEventKind, EventState};
use blitz_traits::node_id::NodeId;
use std::cell::RefCell;
use std::collections::VecDeque;
use std::rc::Rc;

/// The bounded set of DOM event kinds that naivi can bind Vue `v-on` handlers to.
///
/// Generated by `build.rs` from the `@naivi/protocol` SOT — the protocol half
/// (enum, `ALL`, `name`, `to_u8`/`from_u8`, `FromStr`) is generated, do not
/// hand-edit it. Only the blitz mapping impls below are hand-written (TS can't
/// express blitz's Rust `DomEventKind`).
pub use crate::generated::NaiviEventKind;

impl NaiviEventKind {
    /// Map a blitz [`DomEvent`] to the corresponding naivi kind.
    ///
    /// Returns `None` for event kinds naivi does not expose to the guest.
    pub fn from_dom_event(event: &DomEvent) -> Option<Self> {
        match &event.data {
            DomEventData::Click(_) => Some(Self::Click),
            DomEventData::PointerDown(_) => Some(Self::PointerDown),
            DomEventData::PointerUp(_) => Some(Self::PointerUp),
            DomEventData::PointerMove(_) => Some(Self::PointerMove),
            DomEventData::Wheel(_) => Some(Self::Wheel),
            DomEventData::ContextMenu(_) => Some(Self::ContextMenu),
            DomEventData::MouseEnter(_) => Some(Self::MouseEnter),
            DomEventData::MouseLeave(_) => Some(Self::MouseLeave),
            DomEventData::DoubleClick(_) => Some(Self::DblClick),
            DomEventData::KeyDown(_) => Some(Self::KeyDown),
            DomEventData::KeyUp(_) => Some(Self::KeyUp),
            DomEventData::Input(_) => Some(Self::Input),
            _ => None,
        }
    }

    /// Map from a blitz [`DomEventKind`].
    pub fn from_dom_event_kind(kind: DomEventKind) -> Option<Self> {
        match kind {
            DomEventKind::Click => Some(Self::Click),
            DomEventKind::PointerDown => Some(Self::PointerDown),
            DomEventKind::PointerUp => Some(Self::PointerUp),
            DomEventKind::PointerMove => Some(Self::PointerMove),
            DomEventKind::Wheel => Some(Self::Wheel),
            DomEventKind::ContextMenu => Some(Self::ContextMenu),
            DomEventKind::MouseEnter => Some(Self::MouseEnter),
            DomEventKind::MouseLeave => Some(Self::MouseLeave),
            DomEventKind::DoubleClick => Some(Self::DblClick),
            DomEventKind::KeyDown => Some(Self::KeyDown),
            DomEventKind::KeyUp => Some(Self::KeyUp),
            DomEventKind::Input => Some(Self::Input),
            _ => None,
        }
    }

    /// Map to a blitz [`DomEventKind`].
    pub fn to_dom_event_kind(self) -> DomEventKind {
        match self {
            Self::Click => DomEventKind::Click,
            Self::PointerDown => DomEventKind::PointerDown,
            Self::PointerUp => DomEventKind::PointerUp,
            Self::PointerMove => DomEventKind::PointerMove,
            Self::Wheel => DomEventKind::Wheel,
            Self::ContextMenu => DomEventKind::ContextMenu,
            Self::MouseEnter => DomEventKind::MouseEnter,
            Self::MouseLeave => DomEventKind::MouseLeave,
            Self::DblClick => DomEventKind::DoubleClick,
            Self::KeyDown => DomEventKind::KeyDown,
            Self::KeyUp => DomEventKind::KeyUp,
            Self::Input => DomEventKind::Input,
        }
    }
}

/// A single event queued for the naivi guest.
#[derive(Debug, Clone, PartialEq)]
pub struct NaiviEvent {
    /// The JS-assigned **virtual id** of the node that carried the matching
    /// binding (reverse-looked-up from the node's `data-naivi-id` attribute at
    /// queue time, KTD2). `0` when the node has no such attribute (legacy
    /// per-op binding; the guest cannot resolve it).
    pub node: u32,
    /// The event kind.
    pub kind: NaiviEventKind,
    /// Client (viewport-relative) coordinates, when the underlying DOM event
    /// carried them (0.0 otherwise).
    pub client_x: f32,
    pub client_y: f32,
    /// The keyboard key (e.g. `"Enter"`, `"a"`) for key events; empty
    /// otherwise.
    pub key: String,
    /// The physical keyboard code (e.g. `"Enter"`, `"KeyA"`) for key events;
    /// empty otherwise.
    pub code: String,
    /// The full input value for `input` events (the engine's text-input
    /// editor syncs it on every keystroke); empty otherwise.
    pub value: String,
}

/// Receives events drained from [`NaiviDocument`](crate::document::NaiviDocument)'s queue.
///
/// U4 (wasm) and U5 (rquickjs) provide their own impls; the default is a no-op.
pub trait EventSink {
    fn on_event(&mut self, event: NaiviEvent);
}

/// A sink that discards every event (the default).
pub struct NoopEventSink;

impl EventSink for NoopEventSink {
    fn on_event(&mut self, _event: NaiviEvent) {}
}

/// A blitz [`EventHandler`] that only records matching events into the shared queue.
///
/// It never mutates the DOM or calls back into the guest: it consults the
/// binding registry for the first node in the event's chain that has the
/// event kind bound, and pushes the event onto the queue. The queue is
/// drained later by [`NaiviDocument::poll`](crate::document::NaiviDocument::poll),
/// which avoids re-entering blitz's event dispatch while `EventDriver` holds
/// `&mut dyn Document`.
pub struct NaiviEventHandler {
    pub(crate) bindings: Rc<RefCell<NaiviBindings>>,
    pub(crate) queue: Rc<RefCell<VecDeque<NaiviEvent>>>,
}

impl EventHandler for NaiviEventHandler {
    fn handle_event(
        &mut self,
        chain: &[NodeId],
        event: &mut DomEvent,
        doc: &mut dyn Document,
        _event_state: &mut EventState,
    ) {
        let Some(kind) = NaiviEventKind::from_dom_event(event) else {
            return;
        };
        let (client_x, client_y) = client_coords(&event.data);
        let (key, code, value) = event_payload(&event.data);
        let bindings = self.bindings.borrow();
        let Some(node) = chain
            .iter()
            .copied()
            .find(|id| bindings.get(id).is_some_and(|kinds| kinds.contains(&kind)))
        else {
            return;
        };
        // Reverse-look-up the guest's virtual id from the bound node's
        // `data-naivi-id` attribute (KTD2). The frame `bind_event_v` writes
        // the virtual id there; a missing/unparseable value yields 0 (the
        // guest drops the event).
        let virtual_id = doc
            .inner()
            .get_node(node)
            .and_then(|n| n.attr(LocalName::from(DATA_NAIVI_ID)))
            .and_then(|s| s.parse::<u32>().ok())
            .unwrap_or(0);
        drop(bindings);
        self.queue.borrow_mut().push_back(NaiviEvent {
            node: virtual_id,
            kind,
            client_x,
            client_y,
            key,
            code,
            value,
        });
    }
}

/// Cheaply capture client coordinates from a [`DomEventData`] without re-entering blitz.
fn client_coords(data: &DomEventData) -> (f32, f32) {
    use DomEventData::*;
    match data {
        PointerMove(e)
        | PointerDown(e)
        | PointerUp(e)
        | PointerCancel(e)
        | PointerEnter(e)
        | PointerLeave(e)
        | PointerOver(e)
        | PointerOut(e)
        | MouseMove(e)
        | MouseDown(e)
        | MouseUp(e)
        | MouseEnter(e)
        | MouseLeave(e)
        | MouseOver(e)
        | MouseOut(e)
        | TouchStart(e)
        | TouchMove(e)
        | TouchEnd(e)
        | TouchCancel(e)
        | Click(e)
        | ContextMenu(e)
        | DoubleClick(e) => (e.client_x(), e.client_y()),
        Wheel(e) => (e.client_x(), e.client_y()),
        _ => (0.0, 0.0),
    }
}

/// Capture the keyboard/input payload (`(key, code, value)`) from a
/// [`DomEventData`]. Non-keyboard events yield three empty strings.
fn event_payload(data: &DomEventData) -> (String, String, String) {
    match data {
        DomEventData::KeyDown(e) | DomEventData::KeyUp(e) | DomEventData::KeyPress(e) => {
            (e.key.to_string(), e.code.to_string(), String::new())
        }
        DomEventData::Input(e) => (String::new(), String::new(), e.value.clone()),
        _ => (String::new(), String::new(), String::new()),
    }
}
